# Generated by Django 5.2 on 2025-04-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_reference_number_transaction_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
